services:
  stack-proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: stack-proxy:local
    restart: unless-stopped
    ports:
      - "80:80"
      - "5432:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stack-proxy

networks:
  stack-proxy:
    external: true
