version: "3.9"

services:
  stack-proxy:
    image: stack-proxy:local
    container_name: stack-proxy
    restart: unless-stopped
    networks:
      - stack-proxy
    ports:
      - "80:80"
      - "15432:15432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - STACK_PROXY_CONFIG_PATH=/etc/haproxy/generated.cfg
      - STACK_PROXY_NETWORK=stack-proxy
      - STACK_PROXY_HAPROXY_PID=/var/run/haproxy.pid

networks:
  stack-proxy:
    external: true
